version: '3.9'

services:
  # account database
  account-db:
    image: postgres:15
    container_name: account-db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: account
    volumes:
      - account_data:/var/lib/postgresql/data
      - ./init-scripts/account:/docker-entrypoint-initdb.d

  # interest database
  interest-db:
    image: postgres:15
    container_name: interests-db-container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: interest
    volumes:
      - interest_data:/var/lib/postgresql/data
      - ./init-scripts/interest:/docker-entrypoint-initdb.d

  # balance database
  balance-db:
    image: postgres:15
    container_name: balance-db-container
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: balance
    volumes:
      - balance_data:/var/lib/postgresql/data
      - ./init-scripts/balance:/docker-entrypoint-initdb.d

  # logging database
  logging-db:
    image: postgres:15
    container_name: logging-db-container
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logging
    volumes:
      - logging_data:/var/lib/postgresql/data
      - ./init-scripts/logging:/docker-entrypoint-initdb.d

  logging-service:
    build: LoggingService/.
    container_name: logging-service-container
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - logging-db

  account-service:
    build: AccountService/.
    container_name: account-service-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - account-db
      - logging-service

  balance-service:
    build: BalanceService/.
    container_name: balance-service-container
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - balance-db
      - account-service
      - logging-service
  
  interest-service:
    build: InterestService/.
    container_name: interest-service-container
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - interest-db
      - account-service
      - balance-service
      - logging-service



volumes:
  account_data:
  interest_data:
  balance_data:
  logging_data:
